name: shopping_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.5.1
  flutter: 
    sdk: flutter
  google_language_fonts: ^2.0.0
  responsive_framework: ^0.1.5
  flutter_signin_button: ^2.0.0
  auto_size_text: ^3.0.0
  settings_ui: ^1.0.0
  


dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

